steps:
  - id: 'branch name'
    name: 'alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "***********************"
        echo "$BRANCH_NAME"
        echo "***********************"
  - id: 'tf init'
    name: 'hashicorp/terraform:${_TERRAFORM_VERSION}'
    args: ['init', '-upgrade']
    dir: '.'
  - id: 'tf select workspace'
    name: 'hashicorp/terraform:${_TERRAFORM_VERSION}'
    args: ['workspace', 'select', '${BRANCH_NAME}']
    dir: '.'
  - id: 'tf plan'
    name: 'hashicorp/terraform:${_TERRAFORM_VERSION}'
    secretEnv: ['TF_VAR_root_db_password', 'TF_VAR_jwt_secret', 'TF_VAR_jwt_pub']
    args: ['plan', '-var-file=${BRANCH_NAME}.tfvars']
    dir: '.'
  - id: 'tf apply'
    name: 'hashicorp/terraform:${_TERRAFORM_VERSION}'
    secretEnv: ['TF_VAR_root_db_password', 'TF_VAR_jwt_secret', 'TF_VAR_jwt_pub']
    args: ['apply', '-var-file=${BRANCH_NAME}.tfvars', '-auto-approve']
    dir: '.'
  - id: 'rm -rf .terraform'
    name: 'alpine'
    entrypoint: 'rm'
    args: ['-rf', '.terraform']
    dir: '.'
  - id: 'configure kubernetes'
    name: eu.gcr.io/$PROJECT_ID/remote-builder
    env:
     - INSTANCE_ARGS=--image-family remote-builder --network=${BRANCH_NAME}-vpc-network --subnet=subnet-vpc --scopes=https://www.googleapis.com/auth/cloud-platform --preemptible --service-account=${_CLOUD_BUILD_SA} --boot-disk-type=pd-ssd --machine-type=g1-small
     - ZONE=${_ZONE}
     - USERNAME=cloud-user
     - COMMAND=gcloud container clusters get-credentials ${_CONTAINER_CLUSTER} --zone=${_ZONE} && chmod +x ~/workspace/k8s-config/run.sh && cd ~/workspace/k8s-config && BRANCH_NAME=${BRANCH_NAME} ./run.sh ${_CONTAINER_CLUSTER} ${_ZONE}
  - id: 'configure acm for cluster 1'
    name: eu.gcr.io/$PROJECT_ID/remote-builder
    env:
      - INSTANCE_ARGS=--image-family remote-builder --network=${BRANCH_NAME}-vpc-network --subnet=subnet-vpc --scopes=https://www.googleapis.com/auth/cloud-platform --preemptible --service-account=${_CLOUD_BUILD_SA} --boot-disk-type=pd-ssd --machine-type=g1-small
      - ZONE=${_ZONE}
      - USERNAME=cloud-user
      - COMMAND=gcloud container clusters get-credentials ${_CONTAINER_CLUSTER} --zone=${_ZONE} && chmod +x ~/workspace/acm-config/run.sh && cd ~/workspace/acm-config && BRANCH_NAME=${BRANCH_NAME} ./run.sh ${_CONTAINER_CLUSTER} ${_ZONE}
  - id: 'configure kubernetes cluster 2'
    name: eu.gcr.io/$PROJECT_ID/remote-builder
    env:
      - INSTANCE_ARGS=--image-family remote-builder --network=${BRANCH_NAME}-vpc-network-2 --subnet=subnet-vpc-2 --scopes=https://www.googleapis.com/auth/cloud-platform --preemptible --service-account=${_CLOUD_BUILD_SA} --boot-disk-type=pd-ssd --machine-type=g1-small
      - ZONE=${_ZONE_2}
      - USERNAME=cloud-user
      - COMMAND=gcloud container clusters get-credentials ${_CONTAINER_CLUSTER_2} --zone=${_ZONE_2} && chmod +x ~/workspace/k8s-config/run.sh && cd ~/workspace/k8s-config && BRANCH_NAME=${BRANCH_NAME} ./run.sh ${_CONTAINER_CLUSTER_2} ${_ZONE_2}
  - id: 'configure acm for cluster 2'
    name: eu.gcr.io/$PROJECT_ID/remote-builder
    env:
      - INSTANCE_ARGS=--image-family remote-builder --network=${BRANCH_NAME}-vpc-network-2 --subnet=subnet-vpc-2 --scopes=https://www.googleapis.com/auth/cloud-platform --preemptible --service-account=${_CLOUD_BUILD_SA} --boot-disk-type=pd-ssd --machine-type=g1-small
      - ZONE=${_ZONE_2}
      - USERNAME=cloud-user
      - COMMAND=gcloud container clusters get-credentials ${_CONTAINER_CLUSTER_2} --zone=${_ZONE_2} && chmod +x ~/workspace/acm-config/run.sh && cd ~/workspace/acm-config && BRANCH_NAME=${BRANCH_NAME} ./run.sh ${_CONTAINER_CLUSTER_2} ${_ZONE_2}
availableSecrets:
  secretManager:
  - versionName: projects/186160847895/secrets/dev-root-db-password/versions/latest
    env: 'TF_VAR_root_db_password'
  - versionName: projects/186160847895/secrets/jwtRS256/versions/latest
    env: 'TF_VAR_jwt_secret'
  - versionName: projects/186160847895/secrets/jwtRS256public/versions/latest
    env: 'TF_VAR_jwt_pub'
substitutions:
  _ZONE: europe-west4-a
  _ZONE_2: europe-west6-a
  _TERRAFORM_VERSION: 0.14.11
  _CONTAINER_CLUSTER: ${BRANCH_NAME}-cluster-1
  _CONTAINER_CLUSTER_2: ${BRANCH_NAME}-cluster-2
  _CLOUD_BUILD_SA: terraform-service-account@pol-pod11-dev-01.iam.gserviceaccount.com
  _MACHINE_TYPE:
timeout: 3600s
