steps:
  - id: 'configure kubernetes'
    name: eu.gcr.io/$PROJECT_ID/remote-builder
    env:
     - INSTANCE_ARGS=--image-project debian-cloud --image-family debian-10 --network=${BRANCH_NAME}-vpc-network --subnet=subnet-vpc --scopes=https://www.googleapis.com/auth/cloud-platform --preemptible --service-account=${_CLOUD_BUILD_SA}
     - ZONE=${_ZONE}
     - USERNAME=cloud-user
     - COMMAND=gcloud container clusters get-credentials ${_CONTAINER_CLUSTER} --zone=${_ZONE} && chmod +x ~/workspace/scripts/* && TERRAFORM_VERSION=${_TERRAFORM_VERSION} ~/workspace/scripts/install_terraform.sh && chmod +x ~/workspace/k8s-config/destroy.sh && cd ~/workspace/k8s-config && BRANCH_NAME=${BRANCH_NAME} ./destroy.sh
  - id: 'configure kubernetes cluster 2'
    name: eu.gcr.io/$PROJECT_ID/remote-builder
    env:
      - INSTANCE_ARGS=--image-project debian-cloud --image-family debian-10 --network=${BRANCH_NAME}-vpc-network-2 --subnet=subnet-vpc-2 --scopes=https://www.googleapis.com/auth/cloud-platform --preemptible --service-account=${_CLOUD_BUILD_SA}
      - ZONE=${_ZONE}
      - USERNAME=cloud-user
      - COMMAND=gcloud container clusters get-credentials ${_CONTAINER_CLUSTER_2} --zone=${_ZONE_2} && chmod +x ~/workspace/scripts/* && TERRAFORM_VERSION=${_TERRAFORM_VERSION} ~/workspace/scripts/install_terraform.sh && chmod +x ~/workspace/k8s-config/destroy.sh && cd ~/workspace/k8s-config && BRANCH_NAME=${BRANCH_NAME} ./destroy.sh
  - id: 'branch name'
    name: 'alpine'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
        echo "***********************"
        echo "$BRANCH_NAME"
        echo "***********************"
  - id: 'tf init'
    name: 'hashicorp/terraform:${_TERRAFORM_VERSION}'
    args: ['init', '-upgrade']
    dir: '.'
  - id: 'tf select workspace'
    name: 'hashicorp/terraform:${_TERRAFORM_VERSION}'
    args: ['workspace', 'select', '${BRANCH_NAME}']
    dir: '.'
  - id: 'tf plan'
    name: 'hashicorp/terraform:${_TERRAFORM_VERSION}'
    secretEnv: ['TF_VAR_root_db_password', 'TF_VAR_jwt_secret', 'TF_VAR_jwt_pub']
    args: ['plan', '-var-file=${BRANCH_NAME}.tfvars', '-destroy']
    dir: '.'
  - id: 'tf state rm'
    name: 'hashicorp/terraform:${_TERRAFORM_VERSION}'
    secretEnv: ['TF_VAR_root_db_password', 'TF_VAR_jwt_secret', 'TF_VAR_jwt_pub']
    entrypoint: 'sh'
    args: ['-c', 'terraform state rm module.cloud_sql.module.postgresql-db.google_sql_user.default || exit 0']
    dir: '.'
  - id: 'tf destroy'
    name: 'hashicorp/terraform:${_TERRAFORM_VERSION}'
    secretEnv: ['TF_VAR_root_db_password', 'TF_VAR_jwt_secret', 'TF_VAR_jwt_pub']
    args: ['destroy', '-var-file=${BRANCH_NAME}.tfvars', '-auto-approve']
    dir: '.'
availableSecrets:
  secretManager:
  - versionName: projects/186160847895/secrets/dev-root-db-password/versions/latest
    env: 'TF_VAR_root_db_password'
  - versionName: projects/186160847895/secrets/jwtRS256/versions/latest
    env: 'TF_VAR_jwt_secret'
  - versionName: projects/186160847895/secrets/jwtRS256public/versions/latest
    env: 'TF_VAR_jwt_pub'
substitutions:
  _ZONE: europe-west4-a
  _ZONE_2: europe-west6-a
  _TERRAFORM_VERSION: 0.14.11
  _CONTAINER_CLUSTER: ${BRANCH_NAME}-cluster-1
  _CONTAINER_CLUSTER_2: ${BRANCH_NAME}-cluster-2
  _CLOUD_BUILD_SA: terraform-service-account@pol-pod11-dev-01.iam.gserviceaccount.com
timeout: 2700s
