steps:
  - id: 'branch name'
    name: 'alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "***********************"
        echo "$BRANCH_NAME"
        echo "***********************"
  - id: 'tf init'
    name: 'hashicorp/terraform:${_TERRAFORM_VERSION}'
    args: ['init', '-upgrade']
    dir: '.'
  - id: 'tf select workspace'
    name: 'hashicorp/terraform:${_TERRAFORM_VERSION}'
    args: ['workspace', 'select', '${BRANCH_NAME}']
    dir: '.'
  - id: 'tf plan'
    name: 'hashicorp/terraform:${_TERRAFORM_VERSION}'
    secretEnv: ['TF_VAR_root_db_password', 'TF_VAR_jwt_secret', 'TF_VAR_jwt_pub']
    args: ['plan', '-var-file=${BRANCH_NAME}.tfvars']
    dir: '.'
  - id: 'tf apply'
    name: 'hashicorp/terraform:${_TERRAFORM_VERSION}'
    secretEnv: ['TF_VAR_root_db_password', 'TF_VAR_jwt_secret', 'TF_VAR_jwt_pub']
    args: ['apply', '-var-file=${BRANCH_NAME}.tfvars', '-auto-approve']
    dir: '.'
  - id: 'configure kubernetes'
    name: eu.gcr.io/$PROJECT_ID/remote-builder
    env:
     - INSTANCE_ARGS=--image-family=remote-builder --network=${BRANCH_NAME}-vpc-network --subnet=subnet-${BRANCH_NAME}-01 --scopes=https://www.googleapis.com/auth/cloud-platform --preemptible --service-account=${_CLOUD_BUILD_SA} --boot-disk-type=pd-ssd
     - ZONE=${_ZONE}
     - USERNAME=cloud-user
     - COMMAND=gcloud container clusters get-credentials ${_CONTAINER_CLUSTER} --zone=${_ZONE} && chmod +x ~/workspace/k8s-config/run.sh && cd ~/workspace/k8s-config && BRANCH_NAME=${BRANCH_NAME} ./run.sh
availableSecrets:
  secretManager:
  - versionName: projects/186160847895/secrets/dev-secondary-root-db-password/versions/latest
    env: 'TF_VAR_root_db_password'
  - versionName: projects/186160847895/secrets/jwtRS256/versions/latest
    env: 'TF_VAR_jwt_secret'
  - versionName: projects/186160847895/secrets/jwtRS256public/versions/latest
    env: 'TF_VAR_jwt_pub'
substitutions:
  _ZONE: europe-west3-a
  _TERRAFORM_VERSION: 0.14.11
  _CONTAINER_CLUSTER: ${BRANCH_NAME}-cluster
  _CLOUD_BUILD_SA: terraform-service-account@pol-pod11-dev-01.iam.gserviceaccount.com
timeout: 2700s
