steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"
- id: 'build remote-builder'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/remote-builder', 'remote-builder' ]
- id: 'run terraform'
  name: gcr.io/$PROJECT_ID/remote-builder
  env:
    - INSTANCE_ARGS=--image-project debian-cloud --image-family debian-10 --network=${BRANCH_NAME}-vpc-network --subnet=subnet-${BRANCH_NAME}-01 --scopes=https://www.googleapis.com/auth/cloud-platform --preemptible
    - ZONE=${_ZONE}
    - USERNAME=cloud-user
    - COMMAND=chmod +x ~/workspace/scripts/* && TERRAFORM_VERSION=${_TERRAFORM_VERSION} ~/workspace/scripts/install_terraform.sh && cd ~/workspace && BRANCH_NAME=${_BRANCH_NAME} ./scripts/run_terraform.sh
substitutions:
    _BRANCH_NAME: ${BRANCH_NAME}
    _ZONE: europe-central2-a
    _TERRAFORM_VERSION: 0.14.11
    _CONTAINER_CLUSTER: ${BRANCH_NAME}-cluster
timeout: 1800s
