GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${db_user};
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public to ${db_user};
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public to ${db_user};
