name: dependabot
on: [push, pull_request]
jobs:
  version: 2
  updates:
    - package-ecosystem: "terraform"
      directory: "/"
      schedule:
        interval: "daily"
    - package-ecosystem: "docker"
      directory: "/"
      schedule:
        interval: "weekly"