name: style-check
on: [push, pull_request]
jobs:
  terraform-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        ref: ${{ github.ref }}
    - name: run terraform lint
      uses: actionshub/terraform-lint@2.0.1
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        ref: ${{ github.ref }}
    - name: yaml-lint
      uses: ibiqlik/action-yamllint@v3.0.1
      with:
        config_file: .yamllint.yml
