name: tfsec
on: [push, pull_request]
jobs:
  tfsec:
    name: tfsec sarif report
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: Terraform init
        run: cd environments/dev && terraform init

      - name: tfsec
        uses: tfsec/tfsec-sarif-action@master
        with:
          github_token: ${{ secrets.github_token }}
          sarif_file:  tfsec.sarif
