name: tfsec
on: [push, pull_request]
jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract Branch Name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
      - name: Terraform security scan for core branches
        uses: triat/terraform-security-scan@v2.2.3
        if: ${{ env.BRANCH_NAME == 'dev' || env.BRANCH_NAME == 'dev-secondary' || env.BRANCH_NAME == 'prod'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tfsec_actions_working_dir: "environments/${BRANCH_NAME}"
      - name: Terraform security scan for other branches
        uses: triat/terraform-security-scan@v2.2.3
        if: ${{ env.BRANCH_NAME != 'dev' && env.BRANCH_NAME != 'dev-secondary' && env.BRANCH_NAME != 'prod'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tfsec_actions_working_dir: "environments/dev"
